### ISSUE TITLE
Reflection: why was push procedure abandoned?

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#160]
![image](https://user-images.githubusercontent.com/12775400/49218079-1e33d900-f3d8-11e8-9f0c-763fd4108d3d.png)

Please check how this happened. Report here

**Comment by HadadIdan** [comment]
# Report:
It was not abandoned, all of those those warnings belong to Parking Project classes, and are there
because the associated classes are not ready yet - mostly fields that are not in use. They were introduced in https://github.com/TechnionYP5779/team6/commit/52a713e50d41753f1c47ce031f05f630ed9a0312 .

# FAQ:
### Q: Why did it not follow procedure?
A: Simply because it's not ready yet. We only created the fields to have a basic idea how the class is going to look.
### Q: Why did we push it even though it didn't follow procedures?
A: To allow other team members to see the classes and it's fields, allowing them to work on related classes with more clarity. 
### Q: What is the push procedure?
A: The push procedure is documented here: https://github.com/TechnionYP5779/team6/wiki/Push-Procedure
@IlanitSmul @elizabethyeshaayahu320 @Nitzan810 @OrYasso @EyalFaygen @MichaelShohat 
Please make sure to look at this again, as it was updated to Sprint 1.

**Comment by yossigil** [comment]
The push procedure is exactly for cases like this. When you want to forbid people from pushing half baked things. So,

**Comment by EyalFaygen** [comment]
updated the wiki push procedure to prevent this in the future

**Comment by HadadIdan** [comment]
@IlanitSmul @elizabethyeshaayahu320 @Nitzan810 @OrYasso @MichaelShohat
Please make sure to look at this again, as it was updated prevent this in the future.
