### ISSUE TITLE
refactor the code so that it uses box and unbox 

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#81]
code should not include e.g., `x.intValue` or `Short.valueOf(3)`, except for in class box and class unbox

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#110

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#83

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#65

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#80

**Comment by yossigil** [comment]
good

**Comment by yossigil** [comment]
oops, not good. Job not done: 235: : λ instanceof Integer ? cellInt(Box.box((long) ((Integer) λ).intValue()))

**Comment by HadadIdan** [comment]
fixed required in https://github.com/TechnionYP5779/team6/commit/ad3820216f153361659e5cc9f88348218675cd00

classes that I did not refactore to use boxing interfaces:
box.java, boxtest.java, unboxjava, unboxtest,jave : since those create and tests the boxing interfaces.

occurrences that i did not refactore to use boxing interfaces:

1)
```
default String cellReal(final Double ¢) {
    return ¢.longValue() != unbox.unboxThis(¢) ? ¢ + "" : cellInt(box.boxThis(¢.longValue()));
  }
```
since it uses longValue for conversion to double.

2)
```
static String repeat(final int i, final char c) {
    return String.valueOf(new char[i]).replace('\0', c);
  }
```
since it uses valueOf to convert from char to string.

3) to 10.
occurences of valueOf in string.java used to convert from string to a number (Double,Float etc).

11.
```
public final class Bool {
  public static Bool valueOf(final boolean ¢) {
    return new Bool(¢);
  }
```
since it defines the valueOf function in class Bool.

12)
```
  public static Int valueOf(final int ¢) {
    final Int $ = new Int();
    $.inner = ¢;
    return $;
  }
```
since it defines the valueOf function in class Int.

13)
```
  @NotNull public static <T extends Enum<T>> T[] split(final Class<T> clazz, final @NotNull String s) {
    final String @NotNull [] ss = split(s);
    @SuppressWarnings("unchecked") final T @NotNull [] $ = (T[]) Array.newInstance(clazz, ss.length);
    for (int ¢ = 0; ¢ < $.length; ++¢)
      $[¢] = ss[¢] == null ? null : Enum.valueOf(clazz, ss[¢]);
    return $;
  }
```
since it uses Enum.valueOf to return the enum constant of the specified enum type with the specified name.

14)
```
  @Test(expected = NumberFormatException.class) public void ignoring_null() {
    assertNull(Long.valueOf(null));
  }
```
since valueOf is used to convert from String to Long, and more specifically, only used here to assert null.

15. to 16.
occurences of valueOf in stringTest.java used to convert from string to a number (Double,Float etc).

17. to 18.
`    final Bool vot = Bool.valueOf(true), cd = new Bool(), vof = Bool.valueOf(false), cf = new Bool(false);
`
since valueOf is used here to test Bool.valueOf function.

19.
```
  @Test public void valueOfTest() {
    assert new Int(3).inner == Int.valueOf(3).inner;
  }
since valueOf is used here to test Int.valueOf function.
```
